version: '3.8'

services:
  intellifarm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intellifarm-ai
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=5001
    restart: unless-stopped
